# Generated by Django 6.1.1 on 2026-10-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=50)),
                ('imagenes', models.ImageField(upload_to='imagenes/')),
                ('meta_financiera', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_limite', models.DateField()),
                ('informacion_creador', models.TextField()),
                ('progeso_financiero', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contra', models.CharField(max_length=100)),
            ],
        ),
    ]
