# Generated by Django 6.1.1 on 2026-10-05 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campania',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campania',
            name='imagenes',
            field=models.ImageField(blank=True, upload_to='imagenes/'),
        ),
    ]
